### ISSUE TITLE
3.3V connection to SPI pin 2 (5V) destroys Arduino Ethernet shield

### ISSUE THREAD

**Issue by PaulStoffregen** [sparkfun/Teensy_Arduino_Shield_Adapter#6]
This PCB has a terrible design flaw.  When any shield with a 5V connection to pin 2 on the SPI connector is plugged in, the 3.3V and 5V power are shorted together.

Some shields, like older Arduino Ethernet, are **instantly destroyed** by the 5V power applied to their 3.3V circuits!  If all the Teensy pins are soldered, the **Teensy is also killed**.  Very bad.

The destructive path is: 5V power flows from the Teensy Adaptor to the shield on JP10 5V, then through wires on the shield to JP9 pin 2, where it then flow back to the Teensy Adaptor and causes the 3.3V power on the Teensy Adaptor to be driven up to 5V.  If the right-side pins of Teensy are soldered, the 3.3V only circuits on Teensy are destroyed.  The 5V power on the Teensy Adaptor's 3.3V line then flows through JP10 3.3V up to the shield, destroying any 3.3V only circuitry the shield may have.

![sparkfun_teensy_adapter](https://cloud.githubusercontent.com/assets/965463/14409680/39b176ca-fecf-11e5-8d1b-cacd8fdc9bb0.png)

Many modern shields leave SPI pin 2 unconnected.  But some do connect 5V to that pin.  :(

More discussion here:
https://forum.pjrc.com/threads/33280-W5100-Ethernet-shield-preventing-Teensy-3-2-from-reprogramming?p=101999&viewfull=1#post101999

**Comment by lewispg228** [comment]
Hey @PaulStoffregen ,
Sorry for this error in the design. We hope that it hasn't caused to much trouble for you. Thanks for submitting this issue. 

We added an optional jumper in the latest revision (v11). It is now available to buy here:

https://www.sparkfun.com/products/15716

![image](https://user-images.githubusercontent.com/601236/72097818-6e1ee800-32da-11ea-8d46-4e640701bd6a.png)

![image](https://user-images.githubusercontent.com/601236/72097849-85f66c00-32da-11ea-95a8-a16739b3e8ef.png)

Thanks again and we hope this helps with your future projects!

**Comment by PaulStoffregen** [comment]
Thanks for fixing this.  I'm sure it'll help many customers.
